# Generated by Django 3.0.4 on 2021-09-03 03:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('selling_price', models.FloatField()),
                ('brand', models.CharField(choices=[('samsung', 'samsung'), ('oppo', 'oppo'), ('vivo', 'vivo'), ('mi', 'mi'), ('realme', 'realme'), ('oneplus', 'oneplus')], max_length=10)),
                ('product_image1', models.ImageField(upload_to='productimg')),
                ('product_image2', models.ImageField(upload_to='productimg')),
                ('product_image3', models.ImageField(upload_to='productimg')),
                ('product_image4', models.ImageField(upload_to='productimg')),
                ('product_image5', models.ImageField(upload_to='productimg')),
                ('processor', models.CharField(max_length=25)),
                ('battery', models.CharField(max_length=25)),
                ('ram', models.CharField(max_length=5)),
                ('internal', models.CharField(max_length=5)),
                ('expandable', models.CharField(max_length=5)),
                ('display', models.CharField(max_length=15)),
                ('resolution', models.CharField(max_length=15)),
                ('body_length', models.CharField(max_length=5)),
                ('body_width', models.CharField(max_length=5)),
                ('screen_to_body_ratio', models.CharField(max_length=5)),
                ('body_weight', models.CharField(max_length=5)),
                ('refresh_rate', models.CharField(max_length=15)),
                ('front_camera', models.CharField(max_length=5)),
                ('rear_camera', models.CharField(max_length=5)),
                ('bluetooth', models.CharField(max_length=15)),
                ('sim_support', models.CharField(max_length=25)),
                ('usb', models.CharField(max_length=10)),
                ('earphone', models.CharField(max_length=10)),
                ('microphone', models.CharField(max_length=10)),
                ('sensors', models.CharField(max_length=50)),
                ('os', models.CharField(max_length=25)),
                ('available', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50)),
                ('name', models.CharField(max_length=30)),
                ('phone_no', models.CharField(max_length=10)),
                ('customer_image', models.ImageField(upload_to='productimg')),
                ('landmark', models.CharField(max_length=25)),
                ('city', models.CharField(max_length=20)),
                ('zipcode', models.IntegerField()),
                ('state', models.CharField(choices=[('Andaman & Nicobar Islands', 'Andaman & Nicobar Islands'), ('Andra Pradesh', 'Andra Pradesh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Assam', 'Assam'), ('Bihar', 'Bihar'), ('Chandigarh', 'Chandigarh'), ('Chhattisgarh', 'Chhattisgarh'), ('Dadra & Nagar Haveli', 'Dadra & Nagar Haveli'), ('Daman & Diu', 'Daman & Diu'), ('Delhi', 'Delhi'), ('Goa', 'Goa'), ('Gujrat', 'Gujrat'), ('Haryana', 'Haryana'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Jharkhand', 'Jharkhand'), ('Karnataka', 'Karnataka'), ('Kerala', 'Kerala'), ('Lakshadweep', 'Lakshadweep'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Maharashtra', 'Maharashtra'), ('Manipur', 'Manipur'), ('Meghalaya', 'Meghalaya'), ('Mizoram', 'Mizoram'), ('Nagaland', 'Nagaland'), ('Odisha', 'Odisha'), ('Puducherry', 'Puducherry'), ('Punjab', 'Punjab'), ('Rajasthan', 'Rajasthan'), ('Sikkim', 'Sikkim'), ('Tamil Nadu', 'Tamil Nadu'), ('Telangana', 'Telangana'), ('Tripura', 'Tripura'), ('Uttarakhand', 'Uttarakhand'), ('Uttar Pradesh', 'Uttar Pradesh'), ('West Bengal', 'West Bengal')], max_length=50)),
                ('is_seller', models.BooleanField()),
                ('email_verified', models.BooleanField()),
                ('phone_no_verified', models.BooleanField()),
                ('card_type', models.CharField(choices=[('master', 'master'), ('visa', 'visa'), ('credit card', 'credit card'), ('debit card', 'debit card')], max_length=20)),
                ('card_no', models.CharField(max_length=16)),
                ('card_holder', models.CharField(max_length=30)),
                ('valid_from', models.DateField()),
                ('valid_through', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderPlaced',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('ordered_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Accepted', 'Accepted'), ('Packed', 'Packed'), ('On The Way', 'On The Way'), ('Delivered', 'Delivered'), ('Cancel', 'Cancel')], default='pending', max_length=20)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Person')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
