# Generated by Django 3.0.4 on 2021-09-06 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='battery',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='product',
            name='bluetooth',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='product',
            name='body_length',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='product',
            name='body_weight',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='product',
            name='body_width',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='product',
            name='display',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='product',
            name='earphone',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='expandable',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='product',
            name='front_camera',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='product',
            name='internal',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='product',
            name='microphone',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='os',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='product',
            name='processor',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image1',
            field=models.ImageField(blank=True, upload_to='productimg'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image2',
            field=models.ImageField(blank=True, upload_to='productimg'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image3',
            field=models.ImageField(blank=True, upload_to='productimg'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image4',
            field=models.ImageField(blank=True, upload_to='productimg'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image5',
            field=models.ImageField(blank=True, upload_to='productimg'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ram',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='product',
            name='rear_camera',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='product',
            name='refresh_rate',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='product',
            name='resolution',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='product',
            name='screen_to_body_ratio',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='product',
            name='sensors',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='sim_support',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='product',
            name='usb',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
