# Generated by Django 3.0.4 on 2021-09-21 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210914_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='card_holder',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='person',
            name='card_no',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='person',
            name='card_type',
            field=models.CharField(blank=True, choices=[('master', 'master'), ('visa', 'visa'), ('credit card', 'credit card'), ('debit card', 'debit card')], max_length=20),
        ),
        migrations.AlterField(
            model_name='person',
            name='valid_from',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='valid_through',
            field=models.DateField(blank=True),
        ),
    ]
