# Generated by Django 3.0.4 on 2021-09-21 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210921_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='customer_image',
            field=models.FileField(upload_to='productimg'),
        ),
    ]
