# Generated by Django 3.0.4 on 2021-09-21 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210921_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='customer_image',
            field=models.ImageField(upload_to='productimg'),
        ),
    ]
