# Generated by Django 3.0.4 on 2021-09-26 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20210926_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='customer_image',
            field=models.ImageField(blank=True, null=True, upload_to='productimg'),
        ),
    ]
