# Generated by Django 3.0.4 on 2021-09-29 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20210927_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='house_no',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
