# Generated by Django 3.0.4 on 2021-10-19 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20211004_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='first_login',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='house_no',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
